CREATE TABLE IF NOT EXISTS TB_SITUACAO_CARTORIO (
    id VARCHAR(20) NOT NULL,
    nome VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS TB_ATRIBUICAO_CARTORIO (
    id VARCHAR(20) NOT NULL,
    nome VARCHAR(50) NOT NULL,
    situacao BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS TB_CARTORIO (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    observacao VARCHAR(250),
    situacao_id VARCHAR(20) NOT NULL,
    FOREIGN KEY (situacao_id) REFERENCES TB_SITUACAO_CARTORIO(id)
);

CREATE TABLE IF NOT EXISTS TB_ATRIBUICAO_HAS_CARTORIO (
    cartorio_id SERIAL,
    atribuicao_id VARCHAR
);
